#!/usr/bin/env python3
"""
Gera os ícones 16x16 dos botões das telas TC (barra lateral), em PNG, com as cores da marca (UiColors).

Uso (na raiz do workspace):  python3 tools/icons/generate_icons.py

Cada ícone é desenhado como "pixel art" em texto (16 linhas x 16 colunas) ou por código (grades). Para mudar um
ícone, edite o desenho aqui e rode de novo; os PNGs vão para:
  - mods/core/src/main/resources/assets/tccore/textures/gui/icons/     (ícones comuns a todos os mods)
  - mods/cloud-storage/src/main/resources/assets/tccloud/textures/gui/icons/  (modos do Cloud Link)
Sem dependências: o PNG é montado à mão (zlib + struct).
"""
import os
import struct
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CORE = os.path.join(ROOT, "mods/core/src/main/resources/assets/tccore/textures/gui/icons")
CLOUD = os.path.join(ROOT, "mods/cloud-storage/src/main/resources/assets/tccloud/textures/gui/icons")

# Paleta = tokens de UiColors (core). "." = transparente.
PALETTE = {
    ".": (0, 0, 0, 0),
    "O": (0xF9, 0x73, 0x16, 255),  # ACCENT (laranja TCMine)
    "C": (0x22, 0xB8, 0xE8, 255),  # HIGHLIGHT (ciano TCMine)
    "W": (0xE6, 0xE8, 0xEC, 255),  # TEXT
    "M": (0xA3, 0xA8, 0xB3, 255),  # TEXT_MUTED
    "Y": (0xFB, 0xBF, 0x24, 255),  # WARNING
    "S": (0x4A, 0xDE, 0x80, 255),  # SUCCESS
    "R": (0xF8, 0x71, 0x71, 255),  # DANGER
    "K": (0x1B, 0x1E, 0x26, 255),  # fundo da janela
}


def png(path, rows):
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), path
    raw = b"".join(b"\x00" + b"".join(bytes(PALETTE[c]) for c in row) for row in rows)
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
    data = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 16, 16, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def art(text):
    return [line for line in text.strip("\n").split("\n")]


def canvas():
    return [["."] * 16 for _ in range(16)]


def rows_of(grid):
    return ["".join(r) for r in grid]


def grid_icon(cell_rows):
    """Janela com N linhas de células: o tamanho da grade (5 linhas, 8 linhas, janela toda)."""
    g = canvas()
    top = 15 - (cell_rows * 3 + 2)
    for x in range(1, 15):
        g[top][x] = "M"
        g[15 - 1][x] = "M"
    for y in range(top, 15):
        g[y][1] = "M"
        g[y][14] = "M"
    for r in range(cell_rows):
        for c in range(4):
            for dy in range(2):
                for dx in range(2):
                    g[top + 2 + r * 3 + dy][3 + c * 3 + dx] = "C"
    return rows_of(g)


CLOUD_TOP = art("""
................
.....CCCC.......
...CCWWWWCC.....
..CWWWWWWWWCCC..
.CWWWWWWWWWWWWC.
.CWWWWWWWWWWWWC.
..CCCCCCCCCCCC..
""")


def cloud_with(lower):
    return CLOUD_TOP + art(lower)


ICONS_CORE = {
    "help": art("""
................
.....CCCCCC.....
...CC......CC...
..C...OOOO...C..
.C...OO..OO...C.
.C.......OO...C.
C.......OO.....C
C......OO......C
C......OO......C
C..............C
.C.....OO.....C.
.C.....OO.....C.
..C..........C..
...CC......CC...
.....CCCCCC.....
................
"""),
    "sort_amount": art("""
................
.WWWWWWWWW...O..
.WWWWWWWWW...O..
.............O..
.WWWWWWW.....O..
.WWWWWWW.....O..
.............O..
.WWWWW.......O..
.WWWWW.......O..
.............O..
.WWW.......OOOOO
.WWW........OOO.
.............O..
.W..............
.W..............
................
"""),
    "sort_name": art("""
................
..WWW........O..
.W...W.......O..
.W...W.......O..
.WWWWW.......O..
.W...W.......O..
.W...W.......O..
.............O..
.WWWWW.......O..
.....W.......O..
....W......OOOOO
...W........OOO.
..W..........O..
.WWWWW..........
................
................
"""),
    "warning": art("""
................
.......YY.......
......YYYY......
......YKKY......
.....YYKKYY.....
.....YYKKYY.....
....YYYKKYYY....
....YYYKKYYY....
...YYYYKKYYYY...
...YYYYKKYYYY...
..YYYYYYYYYYYY..
..YYYYYKKYYYYY..
.YYYYYYKKYYYYYY.
.YYYYYYYYYYYYYY.
................
................
"""),
    "priority_up": art("""
................
.......OO.......
......OOOO......
.....OOOOOO.....
....OOOOOOOO....
...OOOOOOOOOO...
......OOOO......
......OOOO......
......OOOO......
......OOOO......
................
..WWWWWWWWWWWW..
................
..MMMMMMMMMMMM..
................
................
"""),
    "grid_small": grid_icon(2),
    "grid_medium": grid_icon(3),
    "grid_tall": grid_icon(4),
}
ICONS_CORE["priority_down"] = list(reversed(ICONS_CORE["priority_up"]))

ICONS_CLOUD = {
    # A rede AE2 não vê o canal: só a tela do Link (cadeado).
    "access_terminal": cloud_with("""
................
......MMMM......
.....M....M.....
.....M....M.....
....WWWWWWWW....
....WWWOOWWW....
....WWWOOWWW....
....WWWWWWWW....
................
"""),
    # A rede só guarda: seta entrando na nuvem.
    "access_deposit": cloud_with("""
................
.......SS.......
......SSSS......
.....SSSSSS.....
.......SS.......
.......SS.......
.......SS.......
.......SS.......
................
"""),
    # A rede só retira: seta saindo da nuvem.
    "access_extract": cloud_with("""
................
.......OO.......
.......OO.......
.......OO.......
.......OO.......
.....OOOOOO.....
......OOOO......
.......OO.......
................
"""),
    # A rede guarda e retira.
    "access_full": cloud_with("""
................
...SS......OO...
..SSSS.....OO...
.SSSSSS....OO...
...SS......OO...
...SS....OOOOOO.
...SS.....OOOO..
...SS......OO...
................
"""),
}


def main():
    for name, rows in ICONS_CORE.items():
        png(os.path.join(CORE, name + ".png"), rows)
    for name, rows in ICONS_CLOUD.items():
        png(os.path.join(CLOUD, name + ".png"), rows)
    print(f"{len(ICONS_CORE)} ícones do core e {len(ICONS_CLOUD)} do Cloud Storage gerados.")


if __name__ == "__main__":
    main()
